bankproject/bankapp/urls.py
from . import views
from django.urls import path

app_name = 'bankapp'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login',views.login,name='login'),
    path('',views.home,name='home'),
    path('newpage',views.newpage,name='newpage'),
    path('form',views.form,name='form'),

]

bankproject/bankproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bankproject/bankapp/models.py
from django.db import models

# Create your models here.
class District(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Branches(models.Model):
    dist = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

bankproject/bankapp/views.py
from . models import District,Branches
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib import messages, auth
from django.shortcuts import redirect

# Create your views here.
def home(request):
   return render(request,"base.html")

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password == cpassword:
             if User.objects.filter(username=username).exists():
                 messages.info(request,"Username Taken")
                 return redirect('register')
             else:
                 Users = User.objects.create_user(username=username,password=password)
                 Users.save();
                 return redirect('login')
        else:
            messages.info(request,"password not matching")
            return redirect('register')
    return render(request,"register.html")


def login(request):
   if request.method == 'POST':
      username = request.POST['username']
      password = request.POST['password']
      user = auth.authenticate(username=username, password=password)
      if user is not None:
         auth.login(request,user)
         return render(request,"newpage.html")
      else:
         messages.info(request, "invalid credentials")
         return redirect('login')
   return render(request, "login.html")



def newpage(request):
   return render(request,"form.html")

def form(request):
     if request.method=='POST':
        username1 = request.POST['username1']
        if username1 is not None:
            messages.info(request, "Application Accepted")
     dist = District.objects.All()
     dist_id = request.GET.get('dist_id')
     branches = Branches.objects.filter(dist_id=dist_id).all()
     return render(request, 'form.html', {'branches': branches})

bankproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">

    <link href="{% static 'css/bootstrap.rtl.min.css' %}" rel="stylesheet">
    <script src="http://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %} </title>
</head>
<body>

<div class="container">
   <div class="container">

   {% include 'home.html' %}
       {% block content %}
    {% endblock %}
    </div>

<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</div>
</body>
</html>

bankproject/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    form{
    background-color:pink;
    text-align:center;
    }
  </style>
</head>
<body>
<h2> Registration </h2>
<form action="form" method="post">
    {% csrf_token %}

 <input type="text" name="username1" placeholder="Enter your name"><br>
  <input type="date" name="dob" placeholder="Enter your date of birth"><br>
   <input type="text" name="age" placeholder="Enter your age"><br>
    <label>submit your gender: </label>
    <label> male</label>
    <input type="radio">
    <label>female</label>
    <input type="radio"><br>
    <input type="pno" name="pno" placeholder="Enter your phonenumber"><br>
    <input type="email" name="email" placeholder="Enter your email"><br>
    <input type="text" name="address" placeholder="Enter your address"><br>
    <label>District</label>
    <option value="....">{{ dist.name }}</option>
    <label>Branches</label>
       {% for branches in branches %}
    <option value="{{ dist.name }}">{{ branches.name }}</option>
         {% endfor %}

   <br> <label> Enter your materials provide:</label><br>
    <label>Debit Card</label>
    <input type="checkbox">
    <label>Credit Card</label>
    <input type="checkbox">
    <label>Check book</label>
    <input type="checkbox"><br>
    <input type="submit">
    <a href="{% url 'bankapp:home' %}">Home</a>
</form>

{% for msg in messages %}
<h1> {{msg}} </h1>
{% endfor %}
</body>
</html>

bankproject/templates/home.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bankapp:login' %}">login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Register</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Branches
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Idukki_district">Idukki</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>

          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

bankproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
     <style>
    form{
    background-color:pink;
    text-align:center;
    }
  </style>
</head>
<body>
<form action="login" method="post">
  {% csrf_token %}
  <input type="text" name="username" placeholder="Enter your username"><br>
  <input type="password" name="password" placeholder="Enter your password"><br>
  <input type="submit">
</form>
<a href="{% url 'bankapp:register' %}">Registration</a>
</body>
</html>

bankproject/templates/newpage.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
     <style>
    form{
    background-color:pink;
    text-align:center;
    }
  </style>
</head>
<body>
<form action="newpage" method="post">
  {% csrf_token %}

    <button type="submit">Welcome to form</button>

</form>
</body>
</html>

bankproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
     <style>
    form{
    background-color:pink;
    text-align:center;
    }
  </style>
</head>
<body>
<h2> Registration </h2>
<form action="register/" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter your username"><br>

     <input type="password" name="password" placeholder="Enter your password"><br>
     <input type="password" name="password1" placeholder="Enter your confirm password"><br>
    <input type="submit">

</form>
{% for msg in messages %}
<h1> {{msg}} </h1>
{% endfor %}
</body>
</html>